apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-auth

resources:
  - namespace.yaml
  - rbac.yaml
  - slack-secret.yaml
  - kube-auth-job.yaml
  # Uncomment to use CronJob instead:
  # - kube-auth-cronjob.yaml


