apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-auth-sa
  namespace: kube-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auth-role
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "pods", "secrets"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-auth-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-auth-role
subjects:
- kind: ServiceAccount
  name: kube-auth-sa
  namespace: kube-auth

