{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-auth-manager.serviceAccountName" . }}
  namespace: {{ include "kube-auth-manager.namespace" . }}
  labels:
    {{- include "kube-auth-manager.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-auth-manager.clusterRoleName" . }}
  labels:
    {{- include "kube-auth-manager.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "pods", "secrets", "namespaces", "events"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-auth-manager.clusterRoleBindingName" . }}
  labels:
    {{- include "kube-auth-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-auth-manager.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-auth-manager.serviceAccountName" . }}
  namespace: {{ include "kube-auth-manager.namespace" . }}
{{- end }}

